### ISSUE TITLE
openstack dns command doesn't work

### ISSUE THREAD

**Issue by opnmind** [opentelekomcloud/python-otcextensions#121]
Hello @gtema,

I'm afraid that the dns enhancement is defect. I believe something is wrong wired :).

```shell
$ openstack dns zone list
'ZoneController' object is not callable

$ openstack dns zone show <zone-id>
'Client' object has no attribute 'find_zone'

$ openstack dns zone create --type private --router_id <router-id> test-zone
'Client' object has no attribute 'create_zone'
```

**Comment by gtema** [comment]
Which version do you use? I can not reproduce it currently.

**Comment by opnmind** [comment]
I'm using this one:

```shell
openstackclient==4.0.0
openstacksdk==0.51.0
otcextensions==0.10.0
```

**Comment by opnmind** [comment]
So I renewed the whole virtualenv to update otcextension to 0.10.1:

```shell
$ python -V
Python 3.8.6

$ uname -r
5.8.18-200.fc32.x86_64

$ cat requirements.txt
ansible
otcextensions
openstackclient

pip install -r requirements.txt
Successfully installed 
Successfully installed Babel-2.8.0 MarkupSafe-1.1.1 PrettyTable-0.7.2 PyYAML-5.3.1 WebOb-1.8.6 ansible-2.10.3 ansible-base-2.10.3 aodhclient-2.1.1 appdirs-1.4.4 attrs-20.3.0 certifi-2020.11.8 cffi-1.14.3 chardet-3.0.4 cliff-3.4.0 cmd2-1.3.11 colorama-0.4.4 cryptography-3.2.1 debtcollector-2.2.0 decorator-4.4.2 docker-4.3.1 dogpile.cache-1.0.2 fasteners-0.15 futurist-2.3.0 gnocchiclient-7.0.7 idna-2.10 iso8601-0.1.13 jinja2-2.11.2 jmespath-0.10.0 jsonpatch-1.26 jsonpointer-2.0 jsonschema-3.2.0 keystoneauth1-4.2.1 monotonic-1.5 msgpack-1.0.0 munch-2.5.0 murano-pkg-check-0.3.0 netaddr-0.8.0 netifaces-0.10.9 networkx-2.5 **openstackclient-4.0.0 openstacksdk-0.51.0** os-client-config-2.1.0 os-service-types-1.7.0 osc-lib-2.2.1 oslo.concurrency-4.3.1 oslo.config-8.3.2 oslo.context-3.1.1 oslo.i18n-5.0.1 oslo.log-4.4.0 oslo.serialization-4.0.1 oslo.utils-4.7.0 osprofiler-3.4.0 o**tcextensions-0.10.1** packaging-20.4 pbr-5.5.1 ply-3.11 pyOpenSSL-19.1.0 pycparser-2.20 pydot-1.4.1 pyinotify-0.9.6 pyparsing-2.4.7 pyperclip-1.8.1 pyrsistent-0.17.3 python-barbicanclient-5.0.1 python-cinderclient-7.2.0 python-congressclient-2.0.1 python-dateutil-2.8.1 python-designateclient-4.1.0 python-glanceclient-3.2.2 python-heatclient-2.2.1 python-ironic-inspector-client-4.4.0 python-ironicclient-4.4.0 python-keystoneclient-4.1.1 python-mistralclient-4.1.1 python-muranoclient-2.1.1 python-neutronclient-7.2.1 python-novaclient-17.2.1 python-octaviaclient-2.2.0 python-openstackclient-5.4.0 python-saharaclient-3.2.1 python-searchlightclient-2.1.1 python-senlinclient-2.1.1 python-swiftclient-3.10.1 python-troveclient-5.1.1 python-vitrageclient-4.1.1 python-watcherclient-3.1.1 python-zaqarclient-2.0.1 python-zunclient-4.1.1 pytz-2020.4 requests-2.24.0 requestsexceptions-1.4.0 rfc3986-1.4.0 semantic-version-2.8.5 simplejson-3.17.2 six-1.15.0 stevedore-3.2.2 ujson-4.0.1 urllib3-1.25.11 warlock-1.3.3 wcwidth-0.2.5 websocket-client-0.57.0 wrapt-1.12.1 yaql-1.1.3
``` 

but unfortunately:

```shell
$ openstack --version
openstack 5.4.0

$ openstack help | grep otc | grep dns
  dns ptr record list  List PTR records (otcextensions)
  dns ptr record set  Set PTR record (otcextensions)
  dns ptr record show  Show the PTR record details (otcextensions)
  dns ptr record unset  Delete (restore) PTR record (otcextensions)
  dns recordset create  Create recordset (otcextensions)
  dns recordset delete  Delete Recordset (otcextensions)
  dns recordset list  List recordsets. (otcextensions)
  dns recordset set  Update a Recordset (otcextensions)
  dns recordset show  Show the recordset details (otcextensions)
  dns zone create  Create zone (otcextensions)
  dns zone delete  Delete zone (otcextensions)
  dns zone list  List DNS zones (otcextensions)
  dns zone nameserver list  List DNS zone nameservers (otcextensions)
  dns zone router add  Associate router with a private zone (otcextensions)
  dns zone router remove  Disassociate router with a private zone (otcextensions)
  dns zone set   Update a Zone (otcextensions)
  dns zone show  Show the zone details (otcextensions)

$ openstack --debug dns zone list
'ZoneController' object is not callable
Traceback (most recent call last):
  File "/home/.virtualenvs/ansible-openstack/lib/python3.8/site-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/.virtualenvs/ansible-openstack/lib/python3.8/site-packages/osc_lib/command/command.py", line 39, in run
    return super(Command, self).run(parsed_args)
  File "/home/.virtualenvs/ansible-openstack/lib/python3.8/site-packages/cliff/display.py", line 117, in run
    column_names, data = self.take_action(parsed_args)
  File "/home/.virtualenvs/ansible-openstack/lib/python3.8/site-packages/otcextensions/osclient/dns/v2/zone.py", line 68, in take_action
    data = client.zones(**query)
TypeError: 'ZoneController' object is not callable
clean_up ListZone: 'ZoneController' object is not callable
END return value: 1
```

**Comment by gtema** [comment]
hmm, still no problems on my side, but I have now few potential problems:

- please replace "openstackclient" with "python-openstackclient" in your requirements.txt file. "openstackclient" is installing lot's of additional dependencies (plugins) to OSC that nobody on OTC really needs.
- the conflict might be caused by a clash of otce and python-designateclient, since they use same namespace/target (openstack.dns.v2). Even with it installed I do not have a problem, but this can explain that. Please try dropping it
- additionally you might try/need to check, whether in your "/home/.virtualenvs/ansible-openstack/lib/python3.8/site-packages/" there are no entries for older versions. Every OSC plugin brings it's own "entry-points.txt" file which contains those commands. Might be in your case somehow designateclient takes precedence regarding the client file, but the commands, but the commands coming from OTCE are failing due to incompatibility. If i.e. there is some cache still laying from old version you might have problem

If dropping python-designateclient will help you we will try to establish different setups to try reproducing it on our side. 

P.S. some of colleagues are also seeing this, trying to get details

**Comment by gtema** [comment]
In addition there is ~/.cache/python-entrypoints/ that is keeping the cache

**Comment by opnmind** [comment]
Hi @gtema,

> the conflict might be caused by a clash of otce and python-designateclient, since they use same namespace/target 
> (openstack.dns.v2). Even with it installed I do not have a problem, but this can explain that. Please try dropping it

thanks, the **old python-designateclient** package was the problem. After I changed the requirements to python-openstackclient all problems were gone because there is no python-designateclient anymore.
