### ISSUE TITLE
[DNS] listing zones does not work

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/python-otcextensions#141]
## Description
When running `openstack dns zone list`, following error is shown (with `--debug`):
```
'ZoneController' object is not callable
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cliff/app.py", line 415, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python3.9/site-packages/osc_lib/command/command.py", line 39, in run
    return super(Command, self).run(parsed_args)
  File "/usr/lib/python3.9/site-packages/cliff/display.py", line 117, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/lib/python3.9/site-packages/otcextensions/osclient/dns/v2/zone.py", line 68, in take_action
    data = client.zones(**query)
TypeError: 'ZoneController' object is not callable
clean_up ListZone: 'ZoneController' object is not callable
END return value: 1
```

## Versions
```
Python 3.9.1
openstacksdk: 0.53.0
otcextensions: 0.13.0
```

**Comment by tischrei** [comment]
I tried it with:
openstackclient==4.0.0
openstacksdk==0.55.0
otcextensions==0.13.0
Python 3.8.5 

it is working as expected. Could you notify me if it is still an issue for you.

**Comment by outcatcher** [comment]
Reproducing right now with
```
openstackclient==4.0.0
openstacksdk==0.55.0
otcextensions==0.13.0
python-openstackclient==5.4.0

Python 3.9.2
```

Command to reproduce:
```
$ openstack --os-cloud machine dns zone list                           
'ZoneController' object is not callable
```

**Comment by tischrei** [comment]
Could you provide the output openstack: `--os-cloud machine dns zone list --debug`
via WebEx pls.

**Comment by outcatcher** [comment]
The issue reproduces when there is `python-designateclient` installed:
```shell
...
Installing collected packages: python-designateclient
Successfully installed python-designateclient-4.2.0

~ ⌚ 16:22:58
$ openstack --os-cloud machine dns zone list
'ZoneController' object is not callable

~ ⌚ 16:24:15
$ sudo pip uninstall python-designateclient 
Found existing installation: python-designateclient 4.2.0
Uninstalling python-designateclient-4.2.0:
  Would remove:
    /usr/lib/python3.9/site-packages/designateclient/*
    /usr/lib/python3.9/site-packages/python_designateclient-4.2.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled python-designateclient-4.2.0

~ ⌚ 16:24:59
$ openstack --os-cloud machine dns zone list -c status
+--------+
| status |
+--------+
| ACTIVE |
| ACTIVE |
| ACTIVE |
...
```

**Comment by gtema** [comment]
this is known "bug" in the connection of different clients. It all depends on the order of installed packages. Normally you should not install "openstackclient", but "python-openstackclient" only. Then this will not happen, and you will avoid similar problems in every other case that works in OTC different compared to OpenStack

**Comment by outcatcher** [comment]
I suppose this should be mentioned in the installation guide: https://python-otcextensions.readthedocs.io/en/latest/install/pip_install.html#id1 There are some mentions of `openstackclient`
