### ISSUE TITLE
openstack loadbalancer cmd  is not working anymore

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/python-otcextensions#346]
Hi all,

for any reason the following command is not working anymore:

- openstack --os-cloud  `<cloud>` loadbalancer list 

I get the following error:

```
public endpoint for load-balancer service in eu-ch2 region not found
Traceback (most recent call last):
  File "/home/linux/ansible-env/lib/python3.8/site-packages/cliff/app.py", line 410, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/linux/ansible-env/lib/python3.8/site-packages/cliff/display.py", line 115, in run
    column_names, data = self.take_action(parsed_args)
  File "/home/linux/ansible-env/lib/python3.8/site-packages/octaviaclient/osc/v2/load_balancer.py", line 347, in take_action
    attrs = v2_utils.get_loadbalancer_attrs(self.app.client_manager,
  File "/home/linux/ansible-env/lib/python3.8/site-packages/octaviaclient/osc/v2/utils.py", line 226, in get_loadbalancer_attrs
    client_manager.load_balancer.load_balancer_list
  File "/home/linux/ansible-env/lib/python3.8/site-packages/osc_lib/clientmanager.py", line 45, in __get__
    self._handle = self.factory(instance)
  File "/home/linux/ansible-env/lib/python3.8/site-packages/octaviaclient/osc/plugin.py", line 32, in make_client
    endpoint = instance.get_endpoint_for_service_type(
  File "/home/linux/ansible-env/lib/python3.8/site-packages/osc_lib/clientmanager.py", line 246, in get_endpoint_for_service_type
    endpoint = self.auth_ref.service_catalog.url_for(
  File "/home/linux/ansible-env/lib/python3.8/site-packages/keystoneauth1/access/service_catalog.py", line 392, in url_for
    return self.endpoint_data_for(service_type=service_type,
  File "/home/linux/ansible-env/lib/python3.8/site-packages/keystoneauth1/access/service_catalog.py", line 459, in endpoint_data_for
    raise exceptions.EndpointNotFound(msg)
keystoneauth1.exceptions.catalog.EndpointNotFound: public endpoint for load-balancer service in eu-ch2 region not found
clean_up ListLoadBalancer: public endpoint for load-balancer service in eu-ch2 region not found
END return value: 1
```

**Comment by Polina-Gubina** [comment]
hi @hadoopch! the problem is that eu-ch2 has only elbv3, but now elb client is using elbv2, we need to implement another client for v3, i let you know when it is ready
best regards,
Polina
