### ISSUE TITLE
CentOS 7 Installation issue

### ISSUE THREAD

**Issue by tischrei** [opentelekomcloud/python-otcextensions#41]
I got an issue while installing otcextens without virtual env on CentOS 7. I prepared a fresh environment with the following commands:

```
   $ sudo yum update 
   $ sudo yum install epel-release
   $ sudo yum install gcc python36 python36-devel python36-pip openssl-devel
```

...and run the installation process for otcextensions:

```
[linux@tino-cent ~]$ sudo pip3 install otcextensions
Collecting otcextensions
  Downloading https://files.pythonhosted.org/packages/e8/e7/fbac77ea8ba410925a0f20483ff0a6b45fc191f7f82f177ce30395854fed/otcextensions-0.6.5.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 3.9MB/s
Collecting openstacksdk>=0.29.0 (from otcextensions)
  Downloading https://files.pythonhosted.org/packages/0a/22/b601b1134107ddbc78a5a61bed31c57a5cd75306cc683081662bc72c3df4/openstacksdk-0.31.1-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.0MB/s
Collecting oslo_i18n (from otcextensions)
  Downloading https://files.pythonhosted.org/packages/61/eb/4732a0f12850ef5ada812d4920c6801b7e394f14969864a91927ed853a2f/oslo.i18n-3.23.1-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 10.5MB/s
Collecting pbr!=2.1.0,>=2.0.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/7a/db/6e2fcd67cb1c7c98f54f7f19e925f8d9b23cffb84dab45528a759215fca5/pbr-5.3.1-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 9.6MB/s
Collecting jsonpatch!=1.20,>=1.16 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/a0/e6/d50d526ae2218b765ddbdb2dda14d65e19f501ce07410b375bc43ad20b7a/jsonpatch-1.23-py2.py3-none-any.whl
Collecting os-service-types>=1.7.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/10/2d/318b2b631f68e0fc221ba8f45d163bf810cdb795cf242fe85ad3e5d45639/os_service_types-1.7.0-py2.py3-none-any.whl
Collecting appdirs>=1.3.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting jmespath>=0.9.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting munch>=2.1.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/68/f4/260ec98ea840757a0da09e0ed8135333d59b8dfebe9752a365b04857660a/munch-2.3.2.tar.gz
Collecting six>=1.10.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting keystoneauth1>=3.14.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/46/f2/96af95841631a053d5312f35f2cd7d87c7d56005fde927a18511a4f4798b/keystoneauth1-3.14.0-py2.py3-none-any.whl (302kB)
    100% |████████████████████████████████| 307kB 4.1MB/s
Collecting decorator>=3.4.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting iso8601>=0.1.11 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz (274kB)
    100% |████████████████████████████████| 276kB 4.2MB/s
Collecting dogpile.cache>=0.6.2 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/84/3e/dbf1cfc5228f1d3dca80ef714db2c5aaec5cd9efaf54d7e3daef6bc48b19/dogpile.cache-0.7.1.tar.gz (326kB)
    100% |████████████████████████████████| 327kB 3.6MB/s
Collecting netifaces>=0.10.4 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/0c/9b/c4c7eb09189548d45939a3d3a6b3d53979c67d124459b27a094c365c347f/netifaces-0.10.9-cp36-cp36m-manylinux1_x86_64.whl
Collecting cryptography>=2.1 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/c2/95/f43d02315f4ec074219c6e3124a87eba1d2d12196c2767fadfdc07a83884/cryptography-2.7.tar.gz (495kB)
    100% |████████████████████████████████| 501kB 2.4MB/s
Collecting requestsexceptions>=1.2.0 (from openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/01/8c/49ca60ea8c907260da4662582c434bec98716177674e88df3fd340acf06d/requestsexceptions-1.4.0-py2.py3-none-any.whl
Collecting Babel!=2.4.0,>=2.3.4 (from oslo_i18n->otcextensions)
  Downloading https://files.pythonhosted.org/packages/2c/60/f2af68eb046c5de5b1fe6dd4743bf42c074f7141fe7b2737d3061533b093/Babel-2.7.0-py2.py3-none-any.whl (8.4MB)
    100% |████████████████████████████████| 8.4MB 154kB/s
Collecting jsonpointer>=1.9 (from jsonpatch!=1.20,>=1.16->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/18/b0/a80d29577c08eea401659254dfaed87f1af45272899e1812d7e01b679bc5/jsonpointer-2.0-py2.py3-none-any.whl
Collecting requests>=2.14.2 (from keystoneauth1>=3.14.0->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 9.6MB/s
Collecting stevedore>=1.20.0 (from keystoneauth1>=3.14.0->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/c6/dc/6ee92bccfe3c0448786b30b693e6060d62ec8c4a3ec9a287bac1c1a8d8c9/stevedore-1.30.1-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 10.3MB/s
Collecting asn1crypto>=0.21.0 (from cryptography>=2.1->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 10.0MB/s
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.1->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/5f/bf/6aa1925384c23ffeb579e97a5569eb9abce41b6310b329352b8252cee1c3/cffi-1.12.3-cp36-cp36m-manylinux1_x86_64.whl (430kB)
    100% |████████████████████████████████| 440kB 2.9MB/s
Collecting pytz>=2015.7 (from Babel!=2.4.0,>=2.3.4->oslo_i18n->otcextensions)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 2.6MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.14.2->keystoneauth1>=3.14.0->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 7.4MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.14.2->keystoneauth1>=3.14.0->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 8.4MB/s
Collecting idna<2.9,>=2.5 (from requests>=2.14.2->keystoneauth1>=3.14.0->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 10.1MB/s
Collecting certifi>=2017.4.17 (from requests>=2.14.2->keystoneauth1>=3.14.0->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
    100% |████████████████████████████████| 163kB 7.1MB/s
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.1->openstacksdk>=0.29.0->otcextensions)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 7.2MB/s
Installing collected packages: pbr, jsonpointer, jsonpatch, os-service-types, appdirs, jmespath, six, munch, urllib3, chardet, idna, certifi, requests, stevedore, iso8601, keystoneauth1, decorator, PyYAML, dogpile.cache, netifaces, asn1crypto, pycparser, cffi, cryptography, requestsexceptions, openstacksdk, pytz, Babel, oslo-i18n, otcextensions
  Running setup.py install for munch ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for dogpile.cache ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for cryptography ... done
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 326, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 834, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1037, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 348, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: oslo_i18n .dist-info directory not found

```

**Comment by tischrei** [comment]
I got also the same issue with pip for Python 2.7
